### ISSUE TITLE
Links to this on your blog are broken

### ISSUE THREAD

**Issue by jamesjnadeau** [silentworks/svelte-preschool#1]
Hi @silentworks, I was checking out your site for some help with svelte and google analytics(thanks!):
https://www.donielsmith.com/blog/2018/05/20/how-to-use-google-analytics-with-sapper/

and noticed the projects section in the footer, none of the links were working for me there. Not sure if this is something you care about at the moment :)

Anway, this project was cool to check out as well. Have a good one!

**Comment by silentworks** [comment]
Hi @jamesjnadeau thanks for the heads up. I didn't even notice it stopped working. I will fix it shortly.

**Comment by silentworks** [comment]
Fixed now.
